---
title: "Rmarkdown"
author: "Ming-Yu,Lin"
date: "2020/5/4"
output: html_document
---

#1. Use seq() and rep() to write codes for the following questions:
#(a) Construct a vector as the same output as:
#1 2 3 4 5 2 3 4 5 6 3 4 5 6 7 4 5 6 7 8 5 6 7 8 9
#(b) Construct a vector as the same output as:
#1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5
#(c) Construct a vector as the same output as:
#0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4
#(d) Let more.color be defined as follows.
#Use more.color, seq(), and rep() to create a vector as follows:
#>more.colors<- c("red","yellow","blue","green","magenta","cyan")
#Use more.color, seq(), and rep() to create a vector as follows:
#"red" "yellow" "blue" "yellow" "blue" "green"
#"blue" "green" "magenta" "green" "magenta" "cyan"
#Give the name “color.vec” to this created vector.
#(e) According to (d), how many colors in color.vec?
#(f) According to (d), how many times does each color appear in color.vec?
#(g) Rearrange the order in color.vec by letting the first letter from z to a.

#ans(a)(b)(c)
b<-rep(c(1:5),5)
c<-rep(seq(0,4),rep(5,5))
a<-c(b+c)
b
c
a
#and(d)
more.colors<-c("red","yellow","blue","green","magenta","cyan")
color.vec<-
 c(more.colors[c(seq(1,3),seq(2,4),seq(3,5),seq(4,6))])
color.vec
#ans(e)
unique(color.vec)
#ans(f)
table(color.vec)
#ans(g)
dec.color<-sort(color.vec,decreasing=TRUE)
dec.color


#2. score0 <- c(81.2, 89.6, 64.2, 91.3, 77.4, 84.5, NA, 91.7, 63.5, 84.8,
#NA, 87.8, 87.9, 80.9, 74.8, 64.3, 78.7, 91.3, 76.9, 74.9, 87.6, 88.4)
#(a) Typing mean(score0) and max(score0), what results do you get?
#(b) How to modify mean() and max() so that you can get the numeric answers?
#(c) Delete NA from the vector score0 and assign the name score1 to the new vector.
#What do you get if you type mean(score1) and max(score1)? Are the answers
#the same as those in (b)?
#(d) If I obtain two scores, 67.2 and 89.5, try to change the values in score0 from NA to
#67.2 and 89.5, and assign the name score2 to the new vector.
#(e) What do you get if you type mean(score2) and max(score2)?

#ans(a)
NA and NA
#ans(b)
mean(score0,na.rm=TRUE) and max(score0,na.rm=TRUE)
#ans(c)
score1<-na.omit(score0)
mean(score1) #81.085
max(score1) #91.7
Yes.They are same.
#and(d)
a<-which(is.na(score0))
score2<-score0
score2[a]<-c(67.2,89.5)
score2
#ans(e)
mean(score2) #80.83636
max(score2) #91.7
#TRUE #TRUE

#3.Rolling two fair dices, evaluate the total number that all possible outcomes occur at least once. The events
#are as follows, and each row has two outcomes of dices.
#two.dice <- matrix( c(3, 5, 5, 4, 4, 3, 4, 5, 5, 2, 3, 2, 6, 6, 6,
#3, 6, 2, 1, 2, 5, 6, 1, 5, 6, 1, 3, 6, 6, 3,
#5, 3, 3, 5, 3, 3, 4, 2, 1, 4, 3, 1, 5, 1, 6,
#4, 5, 5, 3, 5, 2, 2, 1, 2, 2, 6, 1, 3, 4, 5,
#6, 4, 3, 3, 6, 1, 2, 1, 4, 5, 1, 1, 2, 3, 6,
#5, 6, 5, 3, 1, 4, 1, 5, 2, 2, 6, 3, 2, 3, 1,
#5, 1, 2, 5, 1, 1, 1, 3, 1, 3, 4, 1, 6, 5, 1,
#5, 6, 6, 5, 5, 2, 4, 1, 3, 5, 2, 1, 1, 1, 1), ncol

#ans3
two.dice <- matrix( c(3, 5, 5, 4, 4, 3, 4, 5, 5, 2, 3, 2, 6, 6, 6, 3, 6, 2, 1, 2, 5, 6, 1, 5, 6,
1, 3, 6, 6, 3, 5, 3, 3, 5, 3, 3, 4, 2, 1, 4, 3, 1, 5, 1, 6, 4, 5, 5, 3, 5, 2, 2, 1, 2, 2, 6, 1, 3,
4, 5, 6, 4, 3, 3, 6, 1, 2, 1, 4, 5, 1, 1, 2, 3, 6, 5, 6, 5, 3, 1, 4, 1, 5, 2, 2, 6, 3, 2, 3, 1, 5,
1, 2, 5, 1, 1, 1, 3, 1, 3, 4, 1, 6, 5, 1, 5, 6, 6, 5, 5, 2, 4, 1, 3, 5, 2, 1, 1, 1, 1), ncol = 2)
 v<- c()
 for(i in 1:60){
  if(length(unique(v))<11){
    v<- c(v,two.dice[i,1] + two.dice[i,2])
 }else{
  break
 }
}
length(v)

#4. Collect students’ scores of math and English as follows:
#Math <- c(79, 61, 76, 40, 51, 98, 48, 34, 54, 51, 45, 61, 75, 42, 32,
#61, 56, 82, 22, 33, 19, 60, 91, 49, 44)
#English <- c(87, 54, 96, 63, 58, 75, 60, 74, 46, 94, 57, 69, 69, 55, 79,
#94, 72, 86, 85, 56, 62, 77, 78, 62, 56)
#(a) Construct a matrix with two columns to collect these scores. The first column is for math and the
#second column is for English. Assign the names for the columns as “Math” and “English”, respectively,
#and assign the ID numbers for the rows from 1 to the total number of the students. Assign the name to
#the matrix as “scores”.
#(b) Classify the students by the scores. Define the student passes the class if the score is greater or equal
#to 60, and the student gets a fail if the score is less than 60. Summarize the number of each of the
#following event:
#A: Math ≥ 60 and English ≥ 60;
#B: Math ≥ 60 and English < 60;
#C: Math < 60 and English ≥ 60;
#D: Math < 60 and English < 60.
#(c) Provide the students’ ID numbers in each category (A, B, C, D).
#ans4(a)
Math <- c(79, 61, 76, 40, 51, 98, 48, 34, 54, 51, 45, 61, 75, 42, 32, 61, 56, 82, 22,
33, 19, 60, 91, 49, 44) English <- c(87, 54, 96, 63, 58, 75, 60, 74, 46, 94, 57, 69, 69,
55, 79, 94, 72, 86, 85, 56, 62, 77, 78, 62, 56)
scores<-
matrix(c(Math,English),ncol=2)
colnames(scores)<-
c("Math","English")
rownames(scores)<-c(1:25)
#ans4(b)
A<-0;B<-0;C<-0;D<-0
for(i in 1:25){
  if(scores[i,1]>=60&&scores[i,2]>=60)A<-
A+1
  else
if(scores[i,1]>=60&&scores[i,2]<60)B<-B+1
  else
if(scores[i,1]<60&&scores[i,2]>=60)C<-C+1
  else{D<-D+1}
}
A;B;C;D
#ans4(C)
A<-c();B<-c();C<-c();D<-c()
for(i in 1:25){
  if(scores[i,1]>=60&&scores[i,2]>=60)A<-
c(A,i)
  else if(scores[i,1]>=60&&scores[i,2]<60)B<-
c(B,i)
  else
if(scores[i,1]<60&&scores[i,2]>=60)C<-
c(C,i)
  else{D<-c(D,i) }
}
A;B;C;D 

#5.When you enter a vector including {5, 10, 11, 1, 0, 3, 8, 10, 4, 0, 1, 6, 7, 10, 7, 0}, treat 0 as a missing value.
#Delete all missing values and evaluate the following questions:
#(1) Sum of the values in the vector;
#(2) The length of the input vector;
#(3) The average of the values in the vector;
#(4) The number of odd values in the vector;
#(5) The number of 10 in the vector;
#(6) The maximum of the values in the vector.
#Using paste( ) and cat( ) (or print( )), prepare the code for the following output:
## (1) Sum: 83
## (2) length: 13
## (3) Average: 6.384615
## (4) # of odd: 7
## (5) # of 10: 3
## (6) Max: 11

#ans5
a<-c(5,10,11,1,0,3,8,10,4,0,1,6,7,10,7,0)
a<-(sort(a))
a<-a[-(1:3)]
a
sum<-paste("(1)Sum :",sum(a))
length<-paste("(2)length :",length(a))
average<-
paste("(3)Average :",round(mean(a),6))
count<-0
for(i in 1:length(a)){
  if(a[i]%%2!=0)count<-count+1
}
odd<-paste("(4)#of odd :",count)
count10<-0
for(i in 1:length(a)){
  if(a[i]==10)count10<-count10+1
}
number<-paste("(5)#of 10 :",count10)
maximum<-paste("(6)Max :",max(a))
cat(sum)
cat(length)
cat(average)
cat(odd)
cat(number)
cat(maximum)